/**
 *  @author    Jakob Otto
 *  @file      stream_transport.cpp
 *  @copyright Copyright 2023 Jakob Otto. All rights reserved.
 *             This file is part of the network-driver project, released under
 *             the GNU GPL3 License.
 */

// Stream transport implementation is header-only via template specializations
// in stream_transport.hpp. Template instantiations are generated by the compiler
// as needed when the template is used.
